ALTER TABLE OrderLines
ALTER COLUMN ID INT NOT NULL;
GO
ALTER TABLE OrderLines
ADD CONSTRAINT PK_OrderLines PRIMARY KEY (ID);
GO
ALTER TABLE OrderLines
ADD CONSTRAINT FK_Products
FOREIGN KEY (ID_Product)
REFERENCES Products (ID);
GO
ALTER TABLE OrderLines
ADD CONSTRAINT CH_Price CHECK (Price > 0);